# SKY
alias sky="cd ~/workspaces/wf/bigsky/z_bigsky && source ~/dev/wf/sky/bin/activate"

# RICHAPPS
alias richapps="cd ~/workspaces/wf/richapps && source ~/dev/wf/richapps/bin/activate"
alias ratests="venvnosetests tests"
alias racover="ratests --with-coverage --cover-package=richapps"

# WEB-BONES
alias bones="cd ~/workspaces/wf/web-bones && source ~/dev/wf/bones/bin/activate"

# WEB-SKIN
alias skin="cd ~/workspaces/wf/web-skin && source ~/dev/wf/skin/bin/activate"

# MAILER
alias mailer="cd ~/workspaces/wf/wf-py-mailer && source ~/dev/wf/mailer/bin/activate"

# DC
alias dc="cd ~/workspaces/wf/datacollections && source ~/dev/wf/dc/bin/activate"

# WCODE
alias wcode="cd ~/workspaces/wf/wcode && source ~/dev/wf/wcode/bin/activate"

# P34
alias p34="cd ~/workspaces/wf/P34/Project34 && source ~/dev/wf/p34/bin/activate"
alias p34-start="p34 && python /Users/chadknight/workspaces/wf/P34/Project34/start.py --dev --no-focus"

# IDENTITY
alias identity="cd ~/workspaces/wf/Identity"

# AUTHMODEL
alias authmodel="cd ~/workspaces/wf/authmodel && source ~/dev/wf/authmodel/bin/activate"

# AUDIT
alias audit_services="cd ~/workspaces/wf/py-audit-services && source ~/dev/wf/audit/bin/activate"

# WF-JS-VENDOR
alias vendor="cd ~/workspaces/wf/wf-js-vendor"

# WF-SDK
alias sdk="cd ~/workspaces/wf/wf-sdk && source ~/dev/wf/sdk/bin/activate"

# OAUTHTWO
alias iam="cd ~/workspaces/wf/py-iam-services && source ~/dev/wf/iam/bin/activate"
alias oauthtwo="cd ~/workspaces/wf/wf-oauthtwo-pyserver && source ~/dev/wf/oauthtwo-pyserver/bin/activate"

# API-TESTING
alias api-testing="cd ~/workspaces/wf/api-testing && source ~/dev/wf/api-testing/bin/activate"

# MAILER
alias mailer="cd ~/workspaces/wf/wf-py-mailer && source ~/dev/wf/mailer/bin/activate"

# BLOG
alias blog="cd ~/workspaces/wf/w-dev-blog && source ~/dev/wf/blog/bin/activate"

# CRGK
alias crgk="cd ~/workspaces/crgk/crgk.github.io"
alias saa="cd ~/workspaces/crgk/saangular && source ~/dev/crgk/saa/bin/activate"
alias isudm="cd ~/workspaces/crgk/isudm && source ~/dev/crgk/isudm/bin/activate"

alias saaserver="dev_appserver.py ."
alias saaconsole="python /usr/local/google_appengine/remote_api_shell.py -s localhost:8080"

alias instinct="cd ~/workspaces/crgk/instinct && source ~/dev/crgk/instinct/bin/activate"

alias battlecode="cd ~/workspaces/crgk/battlecode"
alias dotfiles="cd ~/dotfiles"

alias gowork="cd ~/workspaces/go/src/github.com/Workiva"

# AUTOGENERATED

alias swear-jar="cd /Users/chadknight/workspaces/crgk/swear-jar && source /Users/chadknight/dev/crgk/swear-jar/bin/activate"


alias iam-client="cd /Users/chadknight/workspaces/wf/py-iam-client && source /Users/chadknight/dev/wf/iam-client/bin/activate"

alias funday="cd /Users/chadknight/workspaces/wf/funday && source /Users/chadknight/dev/wf/funday/bin/activate"

alias data_science="cd /Users/chadknight/workspaces/wf/data_science && source /Users/chadknight/dev/wf/data_science/bin/activate"

alias jose="cd /Users/chadknight/workspaces/crgk/python-jose && source /Users/chadknight/dev/crgk/jose/bin/activate"

alias iam-test="cd /Users/chadknight/workspaces/wf/py-iam-services && source /Users/chadknight/dev/wf/iam-test/bin/activate"

alias pypy-work="cd /Users/chadknight/workspaces/go/src/github.com/Workiva/workspaces-api/fixtures && source /Users/chadknight/dev/wf/pypy-work/bin/activate"

alias ws-gen="cd /Users/chadknight/workspaces/wf/workspaces-api/scripts && source /Users/chadknight/dev/wf/ws-gen/bin/activate"

